language: node_js
node_js:
  - "6" # to be removed on "April 2019"
  - "8" # to be removed on "December 2019"
  - "10" # to be removed on "April 2021"
sudo: false
cache:
  directories:
    - node_modules
